package enumeration;

/**
 *
 * @author vitor
 */
public enum OperationType {
    CREATE_CLUSTER,
    DELETE_CLUSTER,
    START_PARGRES,
    INSERT_CONCEPTUAL_WORKFLOW,
    UPDATE_CONCEPTUAL_WORKFLOW,
    DELETE_CONCEPTUAL_WORKFLOW,
    SUBMIT_WORKFLOW_EXECUTION,
    RUN_WORKFLOW_EXECUTION,
    DELETE_WORKFLOW_EXECUTION,
    QUERY_WORKFLOW_EXECUTION,
    RUN_QUERY,
    ABORT_MOUNTED_FOLDERS,
    UNKNOWN,
    DEBUG,
    ABORT_WORKFLOW_EXECUTION,
    MONITOR_WORKFLOW_EXECUTION,
    UPLOAD_BINARY_FILES,
    HELP
}
